=head1 NAME

xde-menu - XDG Compliant Menu for XDE

=head1 SYNOPSIS

xde-menu -- [ OPTIONS ]

=head1 DESCRIPTION

B<xde-menu> is a menu generator, tray menu, and popup menu that can be
used to both generate XDG compliant menus for a number of popular
light-weight window managers as well as providing a system tray and
popup menu.

B<xde-menu> is capable of generating either a complete menu for a number
of well-known window managers, or for generating a sub-menu that can be
included in the root menu of those window managers.

=head1 OPTIONS

B<xde-menu> uses L<getopt_long_only(3)>, so non-ambiguous option
abbreviations are permitted.  B<xde-menu> recognizes the following
options:

=head2 COMMAND OPTIONS

Command options affect the primary operating mode of the program.  Only
one command option can be specified.  B<xde-menu> recognizes the
following command options:

=over

=item B<--monitor>, B<-m>

Specifies that B<xde-menu> is to monitor pertinent directories for
changes and regenerate the menu when changes are detected.  This option
implies the B<--output> option.  This options requires L<libinotify(3)>.

=item B<--replace>, B<-R>

Replace a currently running instance (that was invoked with the
B<--monitor> option).  It is not an error if no other instance is
running.  This option implies the B<--monitor> option.

=item B<--quit>, B<-q>

Ask a currently running instance (that was invoked with the B<--monitor>
option) to quit.  It is not an error if no other instance is running.

=item B<--help>, B<-h>

Print usage information, including the current values of option
defaults, and exit.

=item B<--version>, B<-V>

Print version information and exit.

=item B<--copying>, B<-C>

Print copying information and exit.

=back

=head2 GENERAL OPTIONS

=over

=back

=head1 HISTORY

B<xde-menu> was written for a number of reasons:

=over

=item 1.

Many existing light-weight window manager generators that read XDG
F<.desktop> files do not conform to the XDG menu generation
specifications and, in particular, are incapable of merging menus.

=item 2.

Existing XDG menu generators (such as the SuSE L<xdg_menu(1)> script) do
not properly merge default merge directories and do not observe
C<E<lt>LayoutE<gt>> commands.  Also, they are poor at including icons in
the generated menus.  They, of course, do not generate system tray nor
popup menus either.

=item 3.

Existing XDG menu generators run once and keep cahce information, or
have a C<regenerate> command placed in the menu.  They do not monitor
XDG directories for changes and update menus on changes.

=item 4.

The L<lxpanel(1)> and L<pcmanfm(1)> menu generators do not have any of
the above deficiencies; however, they do not create window manager
specific sub-menus.

=back

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 SEE ALSO

L<xde-style(1)>

=cut

# vim: set sw=4 tw=72 spell spelllang=en_ca:
