=pod

=head1 NAME

xde-winlist - window list for XDE

=head1 SYNOPSIS

B<xde-winlist> [I<OPTIONS>]

=head1 DESCRIPTION

Provides a window list for window managers that do not provide one
themselves or as a better window list for those that provide an inferior
one.  The window list is a list of windows on workspaces with a sub-menu
of actions that can be performed against each window or workspace and is
normally access with a hot key, or by clicking on a window, or by
pressing one or more modifier keys and clicking on a window.
B<xde-winlist> supports all of these activations.  See L</USAGE> and
L</WINDOW MANAGERS> for more information about activation.  For hot key
activation see L<xde-keys(1)>.

=head1 OPTIONS

B<xde-winlist> accepts the following options:

=head2 COMMAND OPTIONS

When specified, the following options alter the primary operating mode
of the program:

=over

=item I<unspecified>

When no command option is specified, the default is to run the window
list without replacing an existing instance.

=item B<--replace>, B<-r>

Run the window list, but replace a running instance of B<xde-winlist>.

=item B<--quit>, B<-q>

Ask a running instance of B<xde-winlist> to quit.

=item B<--help>, B<-h>

Prints usage information and the current options settings and defaults
and exits.

=item B<--version>, B<-V>

Prints the version of the program and a brief copyright statement and
exits.  Parts the first line with L<awk(1)> to obtain just the version
number.

=item B<--copying>, B<-C>

Prints the long copying permission statement and exits.

=back

=head2 GENERAL OPTIONS

The following options are general options:

=over

=item B<--display>, B<-d> I<DISPLAY>

Specify the display to use (overriding the B<DISPLAY> environment
variable).  The default is the value of the B<DISPLAY> environment
variable.

=item B<--screen>, B<-s> I<SCREEN>

Specify the screen number to use when locating the current window and
workspace.  The default is either specified by the B<DISPLAY>
environment variable (which that variable specifies a screen);
otherwise, all screens will be considered.

=item B<--timeout>, B<-t> I<TIMEOUT>

When cycling windows with the mouse or other than a modified keystroke,
or if a key is pressed that does not result in a active window change,
the feedback window will persist for I<TIMEOUT> milliseconds.  The
default is 1000 (or 1 second).

=item B<--border>, B<-B> I<WIDTH>

Places a border around the window list of I<WIDTH> pixels.  The default
is 5 pixels.

=item B<--button>, B<-b> I<BUTTON>

Specifies the button that was used to invoke the pop up.  Defaults to
zero (0).  This should be the button that was used to pop the menu.  A
window manager that invokes this command in response to a button press
should release its passive grab on the button before invoking the window
menu so that the popped up menu can grab the button.  A I<BUTTON> of
zero (0) means that the program was invoked with a key-press instead of
a button.

=item B<--timestamp>, B<-T> I<TIMESTAMP>

Provides the X11 server time-stamp of the event that caused the pop up.

=item B<--cycle>, B<-c>.

Provide a cycle list pop up instead of a list.  Cycle list pop up lists
will not be dismissed until a modifier key is released.

=item B<--hidden>

When listing or cycling windows, also list or cycle through hidden
windows.  The default is to skip hidden windows or windows that have the
skip-window-list attribute.

=item B<--minimized>

When listing or cycling windows, also list or cycle through minimized
windows.  The default is to skip minimized windows or windows that have
the skip-window-list attribute.

=item B<--all-monitors>

When listing or cycling windows, also list or cycle through windows
displayed on monitors other than the current one.  This includes windows
on workspaces that are currently visible on a monitor.

=item B<--all-workspaces>

When cycling windows, also cycle through windows displayed on workspaces
other than the current one.  As windows are cycled, the current
workspace may change as windows from other workspaces are cycled.

=item B<--order>, B<-O> [I<ORDERTYPE>]

Specify the order of the selection list or cycle list.  The I<ORDERTYPE>
specifies which windows to list or cycle through and the order in which
to list or cycle them.  The windows in the list can also be adjusted
using the B<--all-monitors>, B<--all-workspaces>, B<--hidden> and
B<--minimized> options.  The I<ORDERTYPE> can be one of the following:

=over

=item C<client>

Cycle through the windows in the client list in client order.

=item C<stacking>

Cycle through the windows in the stacking order client list in stacking
order (or when not supported, determine stacking order directly and use
the client list in the determined stacking order).

=back

The default is client list order.

=item B<--noactivate>, B<-n>

When selecting or cycling windows, do not activate them.  The default is
to activate the selected or cycled window.   When neither B<--raise> nor
B<--focus> are specified, this results in only highlighting the menu
selection.  Activation of the window will still occur; however, when the
window is selected (a modifier key is released).

=item B<--raise>, B<-r>

When selecting or cycling windows, raise the window.  The default is to
only activate the selected or cycled window and not to explicitly raise
it.  Some window managers raise windows when activated (others do not).
This provides a modicum of control.

=item B<--restore>, B<-R>

When cycling windows, restore the previous cycled window to its former
state before activating or raising the next window.  This is useful when
windows are hidden or minimized and included in the list using the
B<--hidden> or B<--minimized> options.  Only iconification will be
restored: window stacking is not restored.

=item B<--key>, B<-k> [I<KEY>:I<KEY>]

Specify the key combination used to pop up the cycle list.  Modifier
keys have to be specified, only the forward and reverse cycle keys need
be specified.  Pressing the forward key will cycle forward through the
selection; the reverse key, backward.  Only useful when B<--cycle> is
also specified.  The default is C<Alt+Tab:Shift+Alt+Tab>.

=item B<--verbose>, B<-v> [I<LEVEL>]

Increases or sets the output verbosity level to I<LEVEL>.  The default
level is C<1>.  Normal output is printed to standard output.  This
option may be repeated.

=item B<--debug>, B<-D> [I<LEVEL>]

Increases or sets the debugging verbosity level to I<LEVEL>.  The
default level is C<0>.  Debugging output is printed to standard error.
This option may be repeated.

=back

=head2 SESSION MANAGEMENT OPTIONS

X session management options are not used by another user other than the
X11 Session Manager.  The following options are used by X session
management:

=over

=item B<-clientId> I<CLIENTID>

Specifies the X Session Management client identifier of the previously
running session of B<xde-winlist>.

=item B<-restore> I<SAVEFILE>

Specifies the X Session Management filename of a file to which to save
session information.

=back

=head1 USAGE

B<xde-winlist> currently uses F<libwnck+> or F<libwnck> both to identify
the window manager and to provide the window list.  The range and format
of the window actions in the window list provided by F<libwcnk+> is
superior to L<libwnck>.  This use means that B<xde-winlist> does not
current provide much support for window managers that do not have a
modicum of compliance with the EWMH/NetWM specifications.  That may
change in the future.

To locate the menu under a button that was pressed in, for example, an
external panel, where the button has the geometry C<55x20+30+0>, specify
the C<--where='55x20+30+0'> option.  This will properly position the
menu under the button.

=head2 WINDOW MANAGERS

=over

=item L<2bwm(1)>

L<2bwm(1)> does not provide window cycling feedback of its own.
L<2bwm(1)> is supported and should work well.

=item L<adwm(1)>

L<adwm(1)> does not provide window cycling feedback of its own.
L<adwm(1)> is supported and should work well.

=item L<aewm(1)>

L<aewm(1)> does not provide window cycling feedback of its own.
L<aewm(1)> is supported and should work well.

=item L<aewm++(1)>

L<aewm++(1)> is barely ICCCM compliant.  It does not support EWMH/NetWM
nor GNOME/WinWM hints and is, therefore, not supported.

=item L<afterstep(1)>

=item L<awesome(1)>

L<awesome(1)> does not provide window cycling feedback of its own.
L<awesome(1)> is supported and should work well.

=item L<blackbox(1)>

L<blackbox(1)>, when run with L<bbkeys(1)>, provides an adequate window
cycling feedback pop-up of its own and it follows the style of the
window manager.  (Its only real shortcoming is that the feedback window
cannot be centred on the screen or monitor and must be absolutely placed
in the L<bbkeys(1)> configuration file.) When running under
L<blackbox(1)>, B<xde-winlist> will do nothing.

=item L<bspwm(1)>

L<bspwm(1)> does not provide window cycling feedback of its own.
L<bspwm(1)> is supported and should work well.

=item L<ctwm(1)>

L<ctwm(1)> is only GNOME/WinWM compliant and is not yet supported by
F<libwnck+>.  B<xde-winlist> mitigates this to some extent; however, use
L<etwm(1)> instead.

=item L<cwm(1)>

L<cwm(1)> is supported, but it doesn't work that well because L<cwm(1)>
is not placing B<_NET_WM_STATE> on client windows, so F<libwnck+> cannot
locate them.

=item L<dtwm(1)>

L<dtwm(1)> is only ICCCM and OSF/Motif compliant.  F<libwnck+> does not
yet support OSF/Motif/CDE, but B<xde-winlist> mitigates this to some
extent.

=item L<dwm(1)>

L<dwm(1)> is barely ICCCM compliant.  It is not supported.

=item L<echinus(1)>

L<echinus(1)> does not provide window cycling feedback of its own.
L<echinus(1)> is supported and should work well.

=item L<etwm(1)>

L<etwm(1)> does not provide window cycling feedback of its own.
L<etwm(1)> is supported and should work well.

=item L<failsafewm(1)>

L<failsafewm(1)> is minimal and not supported.

=item L<fluxbox(1)>

L<fluxbox(1)> does not provide window cycling feedback of its own.
L<fluxbox(1)> is supported and should work well.

=item L<flwm(1)>

L<flwm(1)> supports GNOME/WinWM but not EWMH/NetWM and is not currently
supported by F<libwnck+>.  B<xde-winlist> mitigates this to some extent.

=item L<fvwm(1)>

L<fvwm(1)> does not provide window cycling feedback of its own.
L<fvwm(1)> is supported and should work well.

=item L<glasswm(1)>

L<glasswm(1)> provides some window control atoms of its own; however,
B<xde-winlist> does not support these at this time.

=item L<goomwwm(1)>

L<goomwwm(1)> does not provide window cycling feedback of its own.
L<goomwwm(1)> is supported and should work well.

=item L<herbstluftwm(1)>

L<herbstluftwm(1)> does not provide window cycling feedback of its own.
L<herbstluftwm(1)> is supported and should work well.

=item L<i3(1)>

L<i3(1)> does not provide window cycling feedback of its own.
L<i3(1)> is supported and should work well.

=item L<icewm(1)>

L<icewm(1)> provides an adequate window cycling feedback pop-up of its
own and it follows the style of the window manager.  Therefore, when
running under L<icewm(1)>, B<xde-winlist> will do nothing.

=item L<jwm(1)>

L<jwm(1)> does not provide window cycling feedback of its own.
L<jwm(1)> is supported and should work well.

=item L<larswm(1)>

L<larswm(1)> is barely ICCCM compliant and is, therefore, not supported.

=item L<matwm2(1)>

L<matwm2(1)> does not provide window cycling feedback of its own.
L<matwm2(1)> is supported and should work well.

=item L<metacity(1)>

L<metacity(1)> provides an adequate window cycling feedback pop-up of its
own and it follows the style of the window manager.  Therefore, when
running under L<metacity(1)>, B<xde-winlist> will do nothing.

=item L<mvwm(1)>

L<mvwm(1)> does not provide window cycling feedback of its own.
L<mvwm(1)> is supported and should work well.

=item L<mwm(1)>

L<mwm(1)> only supports ICCCM and OSF/Motif and does not support
multiple desktops.  It is not supported.

=item L<openbox(1)>

L<openbox(1)> does not provide window cycling feedback of its own.
L<openbox(1)> is supported and should work well.

=item L<pekwm(1)>

L<pekwm(1)> does not provide window cycling feedback of its own.
L<pekwm(1)> is supported and should work well.

=item L<spectrwm(1)>

L<spectrwm(1)> is supported, but it doesn't work that well because, like
L<cwm(1)>, L<spectrwm(1)> is not placing B<_NET_WM_STATE> on client
windows, so F<libwnck+> cannot locate them.  This may have been fixed in
more current versions of L<spectrwm(1)>.

=item L<twm(1)>

L<twm(1)> only supports part of ICCCM and is not supported.

=item L<uwm(1)>

L<uwm(1)> does not provide window cycling feedback of its own.
L<uwm(1)> is supported and should work well.

=item L<velox(1)>

L<velox(1)> is untested.

=item L<vtwm(1)>

L<vtwm(1)> is barely ICCCM compliant and currently unsupported: use
L<etwm(1)> instead.

=item L<waimea(1)>

L<waimea(1)> does not provide window cycling feedback of its own.
L<waimea(1)> is supported and should work well.  Because L<waimea(1)>
has other issues, use the version at
L<https://github.com/bbidulock/waimea> for a corrected version.

=item L<wind(1)>

L<wind(1)> does not provide window cycling feedback of its own.
L<wind(1)> is supported and should work well.

=item L<wm2(1)>

L<wm2(1)> is barely ICCCM compliant and currently unsupported: use its
L<wmx(1)> derivative.

=item L<wmaker(1)>

L<wmaker(1)> provides an adequate window cycling feedback pop-up of its
own and it follows the theme of the window manager.  When running under
L<wmaker(1)>, B<xde-winlist> will do nothing.

=item L<wmii(1)>

L<wmii(1)> does not provide window cycling feedback of its own.
L<wmii(1)> is supported and should work well.

=item L<wmx(1)>

L<wmx(1)> does not provide window cycling feedback of its own.
L<wmx(1)> is supported and should work well.

=item L<xdwm(1)>

L<xdwm(1)> has minimal EWMH/NetWM support.  It should still work
somewhat.

=item L<yeahwm(1)>

L<yeahwm(1)> is barely ICCCM compliant and is currently unsupported.

=back

=head1 HISTORY

I wrote this program particularly for use with L<adwm(1)> and other
tiling window managers that provide no feedback for window cycling
changes and do not typically run will with a panel or window list.  It
provides window cycling feedback without taking up valuable screen
real-estate while the windows are not cycling.  Also, when used with
F<libwnck+>, the window list is multiple-monitor aware and can handle
per-monitor tagged workspaces.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 SEE ALSO

L<xde-keys(1)>

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
