=pod

=head1 NAME

xde-backdrop - background changer for XDE

=head1 SYNOPSIS

B<xde-backdrop> [I<OPTIONS>]

=head1 DESCRIPTION

Provides a per-workspace background changer for window managers that do
not provide any per-workspace backgrounds themselves or for those that
provide an inferior or incomplete set of background facilities.
Backgrounds are the image that is display on the root window.

=head1 OPTIONS

B<xde-setbg> accepts the following options:

=head2 COMMAND OPTIONS

When specified, the following options alter the primary operating mode
of the program:

=over

=item B<--set>, B<-s>

Set the background.  The additional options and arguments are
interpreted as listed in L</OPTIONS>.

=item B<--edit>, B<-e>

Do not set the background, but, rather, launch the background settings
editor.  When a current instance of B<xde-setbg> is running, the running
instance will launch the editor; otherwise, a new B<xde-setbg> daemon
will be started.

=item B<--replace>, B<-r>

Replace a running instance of the program.

=item B<--quit>, B<-q>

Ask a running instance of the program to quit.

=item B<--restart>, B<-r>

Ask a running instance of the program to restart.

=item B<--help>, B<-h>

Prints usage information and the current options settings and defaults
and exits.

=item B<--version>, B<-V>

Prints the version of the program and a brief copyright statement and
exits.  Parts the first line with L<awk(1)> to obtain just the version
number.

=item B<--copying>, B<-C>

Prints the long copying permission statement and exits.

=back

=head2 GENERAL OPTIONS

The following options are general options:

=over

=item B<--grab>, B<-g>

Grab the X Display while setting backgrounds.

=item B<--setroot>, B<-s>

Set the background pixmap on the root window instead of just setting the
root window pixmap properties.

=item B<--nomonitor>, B<-n>

Specifies that B<xde-setbg> should hust set the background(s) and should
not monitor for changes.  Just use L<hsetroot(1)> or some other
background setter instead of this option.

=item B<--theme>, B<-t> I<THEME>

Tells B<xde-setbg> which theme or style is currently being used by the
window manager, overriding automatic detection.

=item B<--delay>, B<-d> I<MILLISECONDS>

Specifies the amount of time in milliesconds to wait after the
appearance (or change) of a window manager before entering full
operation.  If set to zero (0), the program will not wait for a window
manager to appear before entering full operation.  The default is 250
milliseconds.

Many lightweight window managers will invoke some root command that will
set the background on startup.  Without this option, the program will
detect this as though an external root setting utility was used to
customize the backgrounds.

=item B<--areas>, B<-a>

Normally B<xde-setbg> will only distribute backgrounds over workspaces
and not work areas.  (Some window managers that support work areas and
viewports are: L<afterstep(1)>, L<fvwm(1)> and L<vtwm(1)>).

=item B<--verbose>, B<-v> [I<LEVEL>]

Print extra information on standard error while running.  When
I<LEVEL> is not specified, simply increments the output verbosity;
otherwise, the output verbosity is set to I<LEVEL>.

=item B<--debug>, B<-D> [I<LEVEL>]

Print debugging information on standard error while running.  When
I<LEVEL> is not specified, simply increments the debug level; otherwise,
the debug level is set to I<LEVEL>.

=back

=head2 SESSION OPTIONS

Session options are only useful to the session manager and need not be
specified directly by the user.  When specified, these options will be
used to restore the profile from a previous session.

=over

=item B<--clientId> I<CLIENTID>

Specifies the client identifier that was assigned to the program in the
previous session that is being restored.

=item B<--saveFile> I<SAVEFILE>

Specifies the location of the file that was used to save state of the
previous session.

=back

=head1 BEHAVIOR

When the program is executed and an existing instance of the program is
running, it exits unless the B<--replace> options is specified, in which
case the program replaces the running instance.

On the initial invocation of the program for a given X Display, the
program will first await the appearance of an X Window manager.  After a
delay, (configurable with the B<--delay> option), the program will start
operation.

The purpose of waiting until after the window manager to appear is that
most lightweight window managers set the background before or after
startup.  Waiting a short duration after the window manager startup
serves to ignore any changes made to the desktop background during
startup of the desktop environment.

After beginning full operation, the program will complete startup
notification (if it was requested).  It then determines the theme using
XDE properties set by L<xde-style(1)> or L<xde-theme(1)> or from the XDE
gtkrc configuration file.  See L</CONFIGURATION> for how the
configuration file is selected.

The configuration will then be used to set backgrounds on the current
desktop and any additional desktops provided by the window manager and
will monitor for further desktop background changes on the X Display.
When the background settings change, it will change the background of
the root window to the corresponding selected background.  Whenever the
image on the root window is changed using a tool such as L<hsetroot(1)>,
the program will record the change against the desktop and work area and
restore those settings when the desktop and work area change.

Background changes can come from background setting tools (such as
L<hsetroot(1)> or L<xsetroot(1)>), command line invocation arguments,
from changes to the XDE gtkrc file, or from configuration file changes.

The program does not attempt to understand the file and style settings
of the supported lightweight window managers but follows the changes
made by L<xde-style(1)> or L<xde-theme(1)>.  It can detect when an
instance of L<pcmanfm(1)> is controlling the desktop wallpaper.  When a
multiple-background capable window manager is running and present
(currently only L<wmaker(1)>), the program exits and does nothing.

When there is a current background on initial startup, the program
assumes that this is a desktop background that was applied by the
lightweight window manager and ignores its settings.

When the program exits gracefully, it writes its configuration out to
the configuration file, participating in X Session Management when in
effect.  In addition to the background settings, it writes the current
desktop or workspace and work area and viewport to the file.  This
permits it to restore the current desktop or workspace, work area and
view port on session restart or restoration.

=head2 SUMMARY

The user will observe the following when B<xde-setbg> is running:

=over

=item 1.

The desktop background will change when changing desktops or workspaces,
and optionally when changing work areas when enabled.

=item 2.

When meta-themes are changed using the L<xde-style(1)> setting tool, the
set of backgrounds will also be changed.

=item 3.

When a background for a particular desktop or workspace and work area is
changed using a background setting tool, it will remain changed for that
desktop or workspace and work area for the remaining session.

=item 4.

When starting a session when running the program on autostart, the
desktop or workspace and work area and view port will be changed to
match that which was active when the window manager last shut down.
That is, if I was on desktop #5 when I logged out, upon login the
desktop will switch to match the desktop #5.

=item 5.

The set of backgrounds can be set with B<xde-style(1)>.

=item 6.

B<xde-setbg> can be used to change the set of backgrounds during a
session and they will be applied when the session next starts.

=back

=head1 USAGE

B<xde-backdrop> detects window managers and window manager changes
directly and monitors XDE theme changes by monitoring X Window System
properties that are set by L<xde-style(1)> or L<xde-theme(1)>.
Workspace changes are detected directly using EWMH/NetWM, GNOME/WinWM or
OSF/Motif properties and client messages.

Run B<xde-backdrop> in the background or launch it using the supplied
XDG autostart file.  The program takes the following steps:

=over

=head1 CONFIGURATION

A F<.desktop> file is distributed with B<xde-setbg> that can be used to
autostart the program in an XDG compliant environment such as is
provided by the X Desktop Environment.  Startup of the program conforms
to the XDG Startup specification, and the program will notify the
launcher once it has fully started.

=head1 HISTORY

Changing background when desktop or workspaces and work areas was not
possible some decades ago due to the limited memory capabilities of X
Servers at the time.  There is no such limitation today, even on
embedded systems.  The only lightweight window manager with this
capability are L<wmaker(1)> and L<lxde(1)> (running L<pcmanfm(1)> in
B<--desktop> mode).

Placing different backgrounds on different desktops or workspaces and
work areas helps the user of the desktop environment to take notice of
desktop changes in an intuitive way without having to take visual
reference of a desktop pager.  It is a useful feature that is missing
from most lightweight window managers.

L<fvwm(1)> has the "Backer" module that can perform desktop switching in
the same fashion as this program; however, it does not store the full
set of pixmap on the X Display and thus switching between workspaces and
work areas is both sluggish and causes screen flashes.  In particular,
changing desktops rapidly with the scroll wheel is particularly
unresponsive.

I wrote B<xde-setbg> for the X Desktop Environment to overcome the
limitations of the lightweight window managers that it supports.  The
program was initially written in L<perl(1)> but was later converted to a
C<C> language program for speed.

(Note: this program is not terribly useful for dynamic tiling window
managers (such as L<awesome(1)>, L<adwm(1)>, L<echinus(1)> or L<xdwm>)
because the desktop is normally obscured in dynamic tiling window
managers.  There a utility such as B<xde-pager(1)> is more useful.)

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 SEE ALSO

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:

